import os from 'os';

function getComputerUsername() {
  return os.userInfo().username;
}

export default {
	input: 'src/index.js',
	output: {
    banner: (() => `/**
Autogenerated
by ${getComputerUsername()}
at ${new Date()}

This script creates an object \`fmalib\` in the global scope (window), which a method \`handleCurrentPageRedirect\`
that can be called to handle the redirect to the checkout page.

Ensure you're calling \`fmalib.handleCurrentPageRedirect()\` on the page where you want to handle the redirect.
*/`),
    footer: `

// autogenerated: handling the redirect for the current page
fmalib.handleCurrentPageRedirect();
`,
		file: 'dist/fmalib.js',
    name: 'fmalib',
		format: 'umd'
	}
};
