import os from 'os';

function getComputerUsername() {
  return os.userInfo().username;
}

export default {
	input: 'src/index.js',
	output: {
    banner: (() => `/**
Autogenerated
by ${getComputerUsername()}
at ${new Date()}
from https://github.com/Daymannovaes/fma-pages-scripts

Esse script cria um object \`fmalib\` no escopo global (window), que possui um método \`handleCurrentPageRedirect\`
que pode ser chamado para lidar com o redirecionamento para a página de checkout.

Confirme que você está chamando \`fmalib.handleCurrentPageRedirect()\` na página onde deseja lidar com o redirecionamento.

Como o script de redirecionamento funciona:
1. Ao abrir uma página com esse script, por padrão ele vai salvar todos os parâmetros da URL em localStorage.
  por exemplo, se a URL for \`https://www.fma.com.br/vendas1?utm_source=facebook&utm_medium=cpc&utm_campaign=blackfriday\`,
  os parâmetros salvos serão: \`{'utm_source': 'facebook', 'utm_medium': 'cpc', 'utm_campaign': 'blackfriday'}\`
2. Como passo intermediário, o usuário pode sair dessa página por algum motivo (por exemplo ir para um formulário de coleta de dados).
3. Durante esse fluxo, em algum momento o usuário precisa ser redicionado para essa mesma página anterior,
  mas com novos parâmetros que indicam que o usuário deve ser redirecionado para o checkout.
  Esses parâmetros são 2: step=checkout_redirect e checkout_url=<url do checkout>,
  exemplo: \`https://www.fma.com.br/vendas1?step=checkout_redirect&checkout_url=https%3A%2F%2Fpay.hotmart.com%2FSOMEIDHERE%3Foff%3Dsomeoffcode%26checkoutMode%3D10\`
4. Nesse momento, o script vai identificar os parametros de redirecionamento, e irá redirecionar
  o usuário para a URL de checkout, adicionando os parametros salvos em localStorage anteriormente.
  No caso: \`https://pay.hotmart.com/SOMEIDHERE?off=someoffcode&checkoutMode=10&utm_source=facebook&utm_medium=cpc&utm_campaign=blackfriday\`
*/`),
    footer: `

// autogenerated: handling the redirect for the current page
fmalib.handleCurrentPageRedirect();
`,
		file: 'dist/fmalib.js',
    name: 'fmalib',
		format: 'umd'
	}
};
