import os from 'os';
import { defineConfig } from 'vite';

function getComputerUsername() {
  return os.userInfo().username;
}

export default defineConfig({
  build: {
    minify: false,
    lib: {
      entry: 'src/index.ts',
      name: 'fmalib',
      formats: ['umd'],
      fileName: (format) => `fmalib.${format}.js`
    },
    rollupOptions: {
      output: {
        banner: (() => `/*!
Autogenerated
by ${getComputerUsername()}
at ${new Date()}
more details on https://github.com/Daymannovaes/fma-pages-scripts
*/`),
      }
    },
  },
});
